# conditions is to determine hether we can run the task or skip it
- name: Demo on condition
  hosts: localhost
  connection: local
  vars:
    to_install: true

  tasks:
    - name: Print OS Redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: Print OS Ubuntu
      ansible.builtin.debug:
        msg: Ubuntu
      when: os == "ubuntu"

    - name: Get Remainder
      ansible.builtin.shell: echo $(({{number}}%2))
      register: reminder

    - name: Print Even Number
      ansible.builtin.debug:
        msg: Number {{ number }} is even
      when: remainder.stdout == 0

    - name: Boolean condition
      ansible.builtin.debug:
        msg: to_install - true
      when: to_install
